#!/usr/bin/env bash
set -euo pipefail

HOSTNAME_NOW="$(hostname -s 2>/dev/null || hostname)"
TS="$(date -u +%Y%m%d-%H%M%S)"
OUT="/tmp/chatpack-${HOSTNAME_NOW}-${TS}.md"

LLM_HOST="${LLM_HOST:-}"
LLM_URL="${LLM_URL:-http://127.0.0.1:8090}"
if [ -n "$LLM_HOST" ] && [ "${LLM_URL}" = "http://127.0.0.1:8090" ]; then
  LLM_URL="http://${LLM_HOST}:8090"
fi

sec() { echo; echo "## $*"; }
cmd() {
  local title="$1"; shift
  echo; echo "### ${title}"
  echo 
}

{
  echo "# chatpack: ${HOSTNAME_NOW} @ ${TS} UTC"
  echo
  echo "- generated by: llm/scripts/chatpack.sh"
  echo "- LLM_URL: ${LLM_URL}"
  echo

  sec "Host basics"
  cmd "id / date / uname" bash -lc "id; date -u; uname -a"
  cmd "os-release" bash -lc "cat /etc/os-release || true"
  cmd "cpu flags (short)" bash -lc "lscpu | egrep -i \"Model name|Flags\" | sed -n \"1,3p\" || true"

  sec "Mounts + disk"
  cmd "lsblk" bash -lc "lsblk -o NAME,SIZE,TYPE,FSTYPE,MOUNTPOINT || true"
  cmd "findmnt /opt/llm" bash -lc "findmnt /opt/llm || true"
  cmd "ls /opt/llm" bash -lc "ls -la /opt/llm 2>/dev/null | sed -n \"1,120p\" || true"
  cmd "ls /opt/llm/models" bash -lc "ls -la /opt/llm/models 2>/dev/null || true"

  sec "LLM service"
  cmd "systemd status llm-local" bash -lc "systemctl --no-pager --full status llm-local || true"
  cmd "journal tail llm-local" bash -lc "journalctl -u llm-local --no-pager -n 120 || true"
  cmd "LLM health" bash -lc "curl -sS --max-time 3 ${LLM_URL}/health || true"

  sec "Nginx (if installed)"
  cmd "nginx version" bash -lc "nginx -v 2>&1 || true"
  cmd "nginx status" bash -lc "systemctl --no-pager --full status nginx || true"
  cmd "nginx grep (takctl/llm)" bash -lc "grep -RIn -- \"takctl|llm|proxy_pass|/takctl|/llm\" /etc/nginx/sites-enabled /etc/nginx/conf.d 2>/dev/null | sed -n \"1,200p\" || true"

  sec "TAK hints (if present)"
  cmd "takserver status" bash -lc "systemctl --no-pager --full status takserver || true"
  cmd "CoreConfig.xml grep" bash -lc "if [ -f /opt/tak/CoreConfig.xml ]; then egrep -n \"certificateSigning|crl|UserAuthentication|security|tls\" /opt/tak/CoreConfig.xml | sed -n \"1,220p\"; else echo \"no /opt/tak/CoreConfig.xml\"; fi"

  sec "Repo snapshot (if run inside git)"
  cmd "git rev/status" bash -lc "git rev-parse --is-inside-work-tree >/dev/null 2>&1 && { git rev-parse HEAD; git status --porcelain; } || echo \"not a git worktree\""

  sec "Architecture notes"
  cat <<'NOTES'
- Keep LLM host (48hvbat) independent: it serves llama.cpp on 127.0.0.1:8090.
- TAK host may optionally reverse-proxy to the LLM host via nginx (internal only).
- /opt/llm should be an attached EBS volume from a curated snapshot.
- If llama-server needs libgomp.so.1, install libgomp1 on the LLM host.
NOTES
} > "$OUT"

echo "Wrote: $OUT"
