#!/usr/bin/env bash
set -euo pipefail

log() {
  printf '[tak-certs-config] %s\n' "$*"
}

read_kv() {
  local file="$1"
  local key="$2"
  [ -f "$file" ] || return 1
  sed -n "s/^[[:space:]]*${key}[[:space:]]*=[[:space:]]*//p" "$file" | head -n 1
}

read_kv_dir_first_hit() {
  local dir="$1"
  local key="$2"
  [ -d "$dir" ] || return 1

  local f v
  for f in "$dir"/*.conf; do
    [ -f "$f" ] || continue
    v="$(read_kv "$f" "$key" || true)"
    if [ -n "${v:-}" ]; then
      printf '%s\n' "$v"
      return 0
    fi
  done
  return 1
}

read_trimmed_file() {
  local p="$1"
  [ -f "$p" ] || return 1
  tr -d '\r' < "$p" | sed -e 's/[[:space:]]*$//' | head -n 1
}

emit_assign() {
  local key="$1"
  local val="${2-}"
  python3 - "$key" "$val" <<'PY'
import json, sys
k = sys.argv[1]
v = sys.argv[2]
print(f"{k}={json.dumps(v)}")
PY
}

generate_secret() {
  python3 - <<'PY'
import secrets
alphabet = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-_"
print("".join(secrets.choice(alphabet) for _ in range(32)))
PY
}

write_secret_file() {
  local path="$1"
  local value="$2"
  install -d -m 700 /etc/taks/certs
  umask 077
  printf '%s\n' "$value" > "$path"
}

main() {
  local conf="/opt/tak/tools/takctl/conf.d/certs.conf"
  local sec="/opt/tak/tools/takctl/secrets.d/certs.conf"
  local boot_conf_dir="/etc/taks-bootstrap.d/config.d"
  local boot_sec_dir="/etc/taks-bootstrap.d/secrets.d"
  local cert_dir="/etc/taks/certs"
  local dst="/opt/tak/certs/cert-metadata.sh"

  if [ ! -f "$conf" ]; then
    log "missing $conf; will try bootstrap conf.d fallback"
  fi

  mkdir -p /opt/tak/certs
  install -d -m 700 "$cert_dir"

  local COUNTRY STATE CITY ORGANIZATION ORGANIZATIONAL_UNIT CAPASS PASS

  COUNTRY="$(read_kv "$conf" cert_country || true)"
  STATE="$(read_kv "$conf" cert_state || true)"
  CITY="$(read_kv "$conf" cert_city || true)"
  ORGANIZATION="$(read_kv "$conf" cert_organization || true)"
  ORGANIZATIONAL_UNIT="$(read_kv "$conf" cert_organizational_unit || true)"

  CAPASS="$(read_kv "$sec" cert_capass || true)"
  PASS="$(read_kv "$sec" cert_pass || true)"

  if [ -z "${COUNTRY:-}" ]; then
    COUNTRY="$(read_kv_dir_first_hit "$boot_conf_dir" cert_country || true)"
  fi
  if [ -z "${STATE:-}" ]; then
    STATE="$(read_kv_dir_first_hit "$boot_conf_dir" cert_state || true)"
  fi
  if [ -z "${CITY:-}" ]; then
    CITY="$(read_kv_dir_first_hit "$boot_conf_dir" cert_city || true)"
  fi
  if [ -z "${ORGANIZATION:-}" ]; then
    ORGANIZATION="$(read_kv_dir_first_hit "$boot_conf_dir" cert_organization || true)"
  fi
  if [ -z "${ORGANIZATIONAL_UNIT:-}" ]; then
    ORGANIZATIONAL_UNIT="$(read_kv_dir_first_hit "$boot_conf_dir" cert_organizational_unit || true)"
  fi

  if [ -z "${CAPASS:-}" ]; then
    CAPASS="$(read_kv_dir_first_hit "$boot_sec_dir" cert_capass || true)"
  fi
  if [ -z "${PASS:-}" ]; then
    PASS="$(read_kv_dir_first_hit "$boot_sec_dir" cert_pass || true)"
  fi

  COUNTRY="${COUNTRY:-SE}"
  STATE="${STATE:-UnknownState}"
  CITY="${CITY:-UnknownCity}"
  ORGANIZATION="${ORGANIZATION:-TAK}"
  ORGANIZATIONAL_UNIT="${ORGANIZATIONAL_UNIT:-TAKS}"

  if [ -z "${CAPASS:-}" ]; then
    CAPASS="$(read_trimmed_file "$cert_dir/CAPASS" || true)"
  fi
  if [ -z "${PASS:-}" ]; then
    PASS="$(read_trimmed_file "$cert_dir/PASS" || true)"
  fi

  if [ -z "${CAPASS:-}" ]; then
    CAPASS="$(generate_secret)"
    log "generated node-local CAPASS"
  fi
  if [ -z "${PASS:-}" ]; then
    PASS="$(generate_secret)"
    log "generated node-local PASS"
  fi

  write_secret_file "$cert_dir/CAPASS" "$CAPASS"
  write_secret_file "$cert_dir/PASS" "$PASS"

  write_secret_file "$cert_dir/COUNTRY" "${COUNTRY}"
  write_secret_file "$cert_dir/STATE" "${STATE}"
  write_secret_file "$cert_dir/CITY" "${CITY}"
  write_secret_file "$cert_dir/ORGANIZATION" "${ORGANIZATION}"
  write_secret_file "$cert_dir/ORGANIZATIONAL_UNIT" "${ORGANIZATIONAL_UNIT}"

  cat > "$dst" <<EOT
# Generated by TAKS bundle install from takctl runtime config / node-local state
$(emit_assign COUNTRY "${COUNTRY}")
$(emit_assign STATE "${STATE}")
$(emit_assign CITY "${CITY}")
$(emit_assign ORGANIZATION "${ORGANIZATION}")
$(emit_assign ORGANIZATIONAL_UNIT "${ORGANIZATIONAL_UNIT}")
$(emit_assign CAPASS "${CAPASS}")
$(emit_assign PASS "${PASS}")
DIR="files"

if [[ -z "\${STATE}" || -z "\${CITY}" || -z "\${ORGANIZATIONAL_UNIT}" ]]; then
  echo "Please set the following variables before running this script: STATE, CITY, ORGANIZATIONAL_UNIT."
  exit -1
fi

SUBJBASE="/C=\${COUNTRY}/"
if [ -n "\$STATE" ]; then
 SUBJBASE+="ST=\${STATE}/"
fi
if [ -n "\$CITY" ]; then
 SUBJBASE+="L=\${CITY}/"
fi
if [ -n "\$ORGANIZATION" ]; then
 SUBJBASE+="O=\${ORGANIZATION}/"
fi
if [ -n "\$ORGANIZATIONAL_UNIT" ]; then
 SUBJBASE+="OU=\${ORGANIZATIONAL_UNIT}/"
fi
EOT

  chmod 600 "$dst"
  chown tak:tak "$dst" 2>/dev/null || true

  log "wrote $dst from runtime/bootstrap config / node-local state"
  log "persisted node-local cert secret files under $cert_dir"
}

main "$@"
