#!/usr/bin/env bash
set -euo pipefail

log() {
  printf '[tak-certs-config] %s\n' "$*"
}

read_trimmed_file() {
  local p="$1"
  [ -f "$p" ] || return 1
  tr -d '\r' < "$p" | sed -e 's/[[:space:]]*$//' | head -n 1
}

main() {
  local src_dir="/etc/taks/certs"
  local dst="/opt/tak/certs/cert-metadata.sh"

  if [ ! -d "$src_dir" ]; then
    log "no $src_dir present; skipping"
    return 0
  fi

  mkdir -p /opt/tak/certs

  local COUNTRY STATE CITY ORGANIZATION ORGANIZATIONAL_UNIT CAPASS PASS
  COUNTRY="$(read_trimmed_file "$src_dir/COUNTRY" || true)"
  STATE="$(read_trimmed_file "$src_dir/STATE" || true)"
  CITY="$(read_trimmed_file "$src_dir/CITY" || true)"
  ORGANIZATION="$(read_trimmed_file "$src_dir/ORGANIZATION" || true)"
  ORGANIZATIONAL_UNIT="$(read_trimmed_file "$src_dir/ORGANIZATIONAL_UNIT" || true)"
  CAPASS="$(read_trimmed_file "$src_dir/CAPASS" || true)"
  PASS="$(read_trimmed_file "$src_dir/PASS" || true)"

  cat > "$dst" <<EOF
# Generated by TAKS bundle install. Source: /etc/taks/certs/*
COUNTRY=${COUNTRY:-US}
STATE=${STATE}
CITY=${CITY}
ORGANIZATION=${ORGANIZATION:-TAK}
ORGANIZATIONAL_UNIT=${ORGANIZATIONAL_UNIT}
CAPASS=${CAPASS:-atakatak}
PASS=${PASS:-$CAPASS}
DIR=files

if [[ -z \${STATE} || -z \${CITY} || -z \${ORGANIZATIONAL_UNIT} ]]; then
  echo "Please set the following variables before running this script: STATE, CITY, ORGANIZATIONAL_UNIT."
  exit -1
fi

SUBJBASE="/C=\${COUNTRY}/"
if [ -n "\$STATE" ]; then
 SUBJBASE+="ST=\${STATE}/"
fi
if [ -n "\$CITY" ]; then
 SUBJBASE+="L=\${CITY}/"
fi
if [ -n "\$ORGANIZATION" ]; then
 SUBJBASE+="O=\${ORGANIZATION}/"
fi
if [ -n "\$ORGANIZATIONAL_UNIT" ]; then
 SUBJBASE+="OU=\${ORGANIZATIONAL_UNIT}/"
fi
EOF

  chmod 600 "$dst"
  log "wrote $dst"
}

main "$@"
