from __future__ import annotations

import grp
import os
import re
import json
import secrets
import sqlite3
import subprocess
import tempfile
from dataclasses import dataclass
from pathlib import Path

from tak_installer.engine import Context
from tak_installer.runtime_state import get_fqdn
from takctl.onboarding.policy import Policy
from takctl.onboarding.voice_topology import derive_voice_topology


PACKAGE = "mumble-server"
PACKAGES = [
    "mumble-server",
    "python3-zeroc-ice",
    "zeroc-ice-slice",
    "openssl",
]
SERVICE = "mumble-server"
AUTH_SERVICE = "taks-mumble-voice-pin-auth.service"
CONFIG = Path("/etc/mumble/mumble-server.ini")
TLS_DIR = Path("/etc/mumble-server/tls")
HOOK = Path("/etc/letsencrypt/renewal-hooks/deploy/90-mumble-server-cert-refresh")

SECRET_DIR = Path("/opt/tak/tools/takctl/secrets.d")
SECRET_FILE = SECRET_DIR / "murmur.conf"

LEGACY_SECRET_DIR = Path("/opt/tak/bootstrap/secrets.d")
LEGACY_SECRET_FILE = LEGACY_SECRET_DIR / "murmur.conf"

ETC_TAKS_DIR = Path("/etc/taks")
ICE_SECRET_FILE = ETC_TAKS_DIR / "mumble-ice-secret"
SERVICE_PASSWORD_FILE = ETC_TAKS_DIR / "mumble-service-password"

TAKCTL_BIN_DIR = Path("/opt/tak/tools/takctl/bin")
AUTH_BIN = TAKCTL_BIN_DIR / "taks-mumble-voice-pin-auth.py"
AUTH_UNIT = Path("/etc/systemd/system/taks-mumble-voice-pin-auth.service")

SECRET_KEY = "serverpassword"
DB = Path("/var/lib/mumble-server/mumble-server.sqlite")
DEFAULT_CHANNELS: list[str] = []


AUTH_SCRIPT = r"""#!/usr/bin/env python3
from __future__ import annotations

import datetime as dt
import hashlib
import json
import re
import secrets
import subprocess
import sys
import tempfile
import traceback
from pathlib import Path
from typing import Any

import Ice

SLICE = "/etc/mumble/MumbleServer.ice"
ICE_INCLUDE = "/usr/share/ice/slice"
SECRET_FILE = Path("/etc/taks/mumble-ice-secret")
STATE = Path("/opt/tak/tools/takctl/state/voice_pin_auth/users.json")
VOICE_ONBOARDING_ROOT = Path("/opt/tak/tools/martine/state/voice_onboarding")
LOG = Path("/var/log/taks-mumble-voice-pin-auth.log")
TAKSERVER_MESSAGING_LOG = Path("/opt/tak/logs/takserver-messaging.log")
SERVICE_PASSWORD_FILE = Path("/etc/taks/mumble-service-password")

Ice.loadSlice(f"-I{ICE_INCLUDE} --all {SLICE}")
import MumbleServer  # type: ignore  # generated by Ice.loadSlice


def utc_now() -> dt.datetime:
    return dt.datetime.now(dt.timezone.utc)


def iso_now() -> str:
    return utc_now().replace(microsecond=0).isoformat().replace("+00:00", "Z")


def log(msg: str) -> None:
    line = f"{iso_now()} {msg}"
    print(line, flush=True)
    with LOG.open("a") as f:
        f.write(line + "\n")


def _new_pin() -> str:
    return f"{secrets.randbelow(10000):04d}"


def _sync_voice_specs(state: dict[str, Any]) -> dict[str, Any]:
    records = state.setdefault("records", {})
    if not VOICE_ONBOARDING_ROOT.exists():
        return state

    for spec_path in sorted(VOICE_ONBOARDING_ROOT.glob("*/voice_spec.json")):
        try:
            spec = json.loads(spec_path.read_text())
        except Exception:
            continue

        target = spec.get("target") or {}
        callsign = str(target.get("callsign") or "").strip()
        uid = str(target.get("uid") or "").strip()
        if not callsign or not uid:
            continue

        key = callsign.upper()
        rec = records.setdefault(key, {})
        rec["callsign"] = callsign
        rec["uid"] = uid
        rec.setdefault("voice_pin", _new_pin())
        rec.setdefault("enabled", True)
        rec.setdefault("allow_empty_vx_password", True)
        rec.setdefault("created_at", iso_now())
        rec["source_voice_spec"] = str(spec_path)

    return state


def load_state() -> dict[str, Any]:
    try:
        state = json.loads(STATE.read_text())
    except Exception:
        state = {"schema": "taks.voice.pin_users.v1", "records": {}}

    return _sync_voice_specs(state)


def save_state(state: dict[str, Any]) -> None:
    STATE.parent.mkdir(parents=True, exist_ok=True)
    tmp = STATE.with_suffix(".tmp")
    state["updated_at"] = iso_now()
    tmp.write_text(json.dumps(state, indent=2, sort_keys=True) + "\n")
    tmp.chmod(0o600)
    tmp.replace(STATE)


def parse_claimed_callsign(name: str) -> str:
    s = (name or "").strip()
    s = s.split("---", 1)[0]
    s = s.split("/", 1)[0]
    return s.strip().upper()


def x509_summary_from_der(der: bytes) -> dict[str, str]:
    out = {
        "subject": "",
        "issuer": "",
        "serial": "",
        "fingerprint_sha256": "",
        "cn": "",
    }

    with tempfile.TemporaryDirectory() as td:
        der_path = Path(td) / "cert.der"
        der_path.write_bytes(der)

        cmd = [
            "openssl", "x509",
            "-inform", "DER",
            "-in", str(der_path),
            "-noout",
            "-subject",
            "-issuer",
            "-serial",
            "-fingerprint",
            "-sha256",
        ]
        p = subprocess.run(cmd, text=True, capture_output=True)
        raw = (p.stdout or "") + (p.stderr or "")
        for line in raw.splitlines():
            line = line.strip()
            if line.startswith("subject="):
                out["subject"] = line.removeprefix("subject=").strip()
            elif line.startswith("issuer="):
                out["issuer"] = line.removeprefix("issuer=").strip()
            elif line.startswith("serial="):
                out["serial"] = line.removeprefix("serial=").strip()
            elif "Fingerprint=" in line:
                out["fingerprint_sha256"] = line.split("Fingerprint=", 1)[1].strip()

    m = re.search(r"(?:^|[,/ ]+)CN\s*=\s*([^,/|]+)", out["subject"])
    if m:
        out["cn"] = m.group(1).strip()

    return out


def recent_takserver_seen(callsign: str, uid: str) -> tuple[bool, str]:
    if not TAKSERVER_MESSAGING_LOG.exists():
        return False, "takserver-messaging.log missing"

    callsign_re = re.escape(callsign)
    uid_re = re.escape(uid)
    pat = re.compile(
        rf"Set client for subscription: tls:\d+ to {callsign_re} \({uid_re}\) source=([0-9a-fA-F:.]+):(\d+)"
    )

    last = None
    try:
        lines = TAKSERVER_MESSAGING_LOG.read_text(errors="replace").splitlines()
    except Exception as e:
        return False, f"could not read TAKServer log: {e!r}"

    for line in lines[-4000:]:
        m = pat.search(line)
        if m:
            last = line.strip()

    if not last:
        return False, "no recent/current TAKServer subscription log match"

    return True, last


def user_id_for(callsign: str, uid: str, identity: str = "") -> int:
    # VX may open multiple Mumble sessions for the same TAK callsign/UID,
    # one per selected voice channel. Include the VX-provided unique name suffix
    # so Murmur does not disconnect the previous one as a ghost.
    h = hashlib.sha256(f"{callsign}|{uid}|{identity}".encode()).digest()
    return 100000 + int.from_bytes(h[:4], "big") % 2000000000


def service_user_id_for(name: str) -> int:
    label = name or "taks-local-service"
    h = hashlib.sha256(f"local-service|{label}".encode()).digest()
    return 2100000000 + int.from_bytes(h[:3], "big") % 40000000


def load_service_passwords() -> set[str]:
    passwords: set[str] = set()

    for path in (
        SERVICE_PASSWORD_FILE,
        Path("/opt/tak/tools/takctl/secrets.d/murmur.conf"),
        Path("/opt/tak/bootstrap/secrets.d/murmur.conf"),
        Path("/etc/taks-bootstrap.d/secrets.d/murmur.conf"),
    ):
        try:
            text = path.read_text().strip()
        except Exception:
            continue

        if not text:
            continue

        if "\n" not in text and "=" not in text:
            passwords.add(text.strip().strip('"').strip("'"))

        for line in text.splitlines():
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            k, v = line.split("=", 1)
            lk = k.lower()
            if "mumble" in lk or "serverpassword" in lk or "pass" in lk or "password" in lk:
                v = v.strip().strip('"').strip("'")
                if v:
                    passwords.add(v)

    return {p for p in passwords if p}


class VoicePinAuthenticator(MumbleServer.ServerAuthenticator):
    def authenticate(self, name, pw, certificates, certhash, certstrong, current=None):
        callsign = parse_claimed_callsign(name)
        state = load_state()
        records = state.get("records") or {}
        rec = records.get(callsign) or {}

        try:
            certs = list(certificates or [])
            pw = pw or ""
            cert_cn = ""
            cert_sha256 = ""

            if certs:
                der = bytes(certs[0])
                cert_sha256 = hashlib.sha256(der).hexdigest()
                cert_cn = x509_summary_from_der(der).get("cn") or ""

            log(
                "AUTH_ATTEMPT "
                f"name={name!r} callsign={callsign!r} "
                f"pw_len={len(pw)} cert_count={len(certs)} "
                f"cert_cn={cert_cn!r} certhash={certhash!r} certstrong={certstrong!r}"
            )

            # Local/service clients such as Martine, takctl health checks, and dump
            # tools do not present the ATAK/VX self-signed cert. Let them in only
            # when they know the service Mumble password. Murmur's authenticator
            # callback does not pass the client source IP, so we cannot safely key
            # this on 127.0.0.1 here.
            if not certs:
                if str(pw) in load_service_passwords():
                    svc_name = str(name or "taks-local-service")
                    svc_id = service_user_id_for(svc_name)
                    log(f"AUTH_ACCEPT_SERVICE name={svc_name!r} user_id={svc_id}")
                    return (svc_id, svc_name, [])
                log(f"AUTH_REJECT_SERVICE name={name!r} reason=missing_or_bad_service_password")
                return (-1, "", [])

            def reject(reason: str):
                log(f"AUTH_REJECT callsign={callsign!r} uid={cert_cn!r} reason={reason}")
                rec2 = state.setdefault("records", {}).setdefault(callsign or "UNKNOWN", {})
                failures = list(rec2.get("failed_attempts") or [])
                failures.append({"ts": iso_now(), "reason": reason})
                rec2["failed_attempts"] = failures[-20:]
                rec2["last_failure_at"] = iso_now()
                rec2["last_failure_reason"] = reason
                save_state(state)
                return (-1, "", [])

            if not callsign:
                return reject("missing_callsign")

            if not rec:
                return reject("unknown_callsign")

            if not rec.get("enabled", True):
                return reject("voice_disabled")

            expected_uid = str(rec.get("uid") or "").strip()
            if not cert_cn:
                return reject("missing_vx_cert_cn")

            if cert_cn != expected_uid:
                return reject(f"uid_mismatch expected={expected_uid!r} got={cert_cn!r}")

            # Current ATAK VX sends an empty password even when the user tries to
            # enter one. The real gate is UID/callsign correlation with a recent
            # TAKServer TLS subscription.
            seen_ok, seen_detail = recent_takserver_seen(callsign, expected_uid)
            if not seen_ok:
                return reject("no_takserver_uid_callsign_presence: " + seen_detail)

            user_id = user_id_for(callsign, expected_uid, name)

            rec.setdefault("mumble_identities", {})
            rec["mumble_identities"][str(user_id)] = {
                "name": name,
                "callsign": callsign,
                "uid": expected_uid,
                "last_seen_at": iso_now(),
            }
            rec["allow_empty_vx_password"] = True
            rec["last_success_at"] = iso_now()
            rec["last_vx_cert_cn"] = cert_cn
            rec["last_vx_cert_sha256_der"] = cert_sha256
            rec["last_murmur_certhash"] = certhash
            rec["last_certstrong"] = bool(certstrong)
            rec["last_takserver_presence"] = seen_detail
            rec["failed_attempts"] = []
            records[callsign] = rec
            state["records"] = records
            save_state(state)

            log(
                "AUTH_ACCEPT "
                f"callsign={callsign!r} uid={expected_uid!r} "
                f"user_id={user_id} vx_cert_sha256={cert_sha256}"
            )

            return (user_id, name, [])

        except Exception:
            log("AUTH_EXCEPTION " + traceback.format_exc().replace("\n", " | "))
            return (-1, "", [])

    def getInfo(self, id, current=None):
        return (False, {})

    def nameToId(self, name, current=None):
        callsign = parse_claimed_callsign(name)
        state = load_state()
        rec = (state.get("records") or {}).get(callsign) or {}
        uid = str(rec.get("uid") or "")
        if callsign and uid:
            return user_id_for(callsign, uid, name)
        return -2

    def idToName(self, id, current=None):
        state = load_state()
        for callsign, rec in (state.get("records") or {}).items():
            identities = rec.get("mumble_identities") or {}
            if str(id) in identities:
                return str(identities[str(id)].get("name") or rec.get("callsign") or callsign)
        return ""

    def idToTexture(self, id, current=None):
        return b""


def install_authenticator() -> None:
    secret = SECRET_FILE.read_text().strip()

    init_data = Ice.InitializationData()
    init_data.properties = Ice.createProperties()
    init_data.properties.setProperty("Ice.ImplicitContext", "Shared")

    communicator = Ice.initialize(sys.argv, init_data)
    communicator.getImplicitContext().setContext({"secret": secret})

    adapter = communicator.createObjectAdapterWithEndpoints(
        "TaksMumbleVoicePinAuth",
        "tcp -h 127.0.0.1",
    )

    servant = VoicePinAuthenticator()
    auth_proxy = MumbleServer.ServerAuthenticatorPrx.uncheckedCast(
        adapter.addWithUUID(servant)
    )

    meta_base = communicator.stringToProxy("Meta:tcp -h 127.0.0.1 -p 6502")
    meta = MumbleServer.MetaPrx.checkedCast(meta_base)
    if not meta:
        raise RuntimeError("Could not cast Meta proxy")

    servers = []
    for method in ("getBootedServers", "getAllServers"):
        try:
            servers = list(getattr(meta, method)())
            if servers:
                log(f"using meta.{method}(), servers={len(servers)}")
                break
        except Exception as e:
            log(f"meta.{method} failed: {e!r}")

    if not servers:
        raise RuntimeError("No Murmur virtual servers found via ICE")

    adapter.activate()

    for server in servers:
        sid = server.id()
        server.setAuthenticator(auth_proxy)
        log(f"setAuthenticator installed on server_id={sid}")

    log("READY voice PIN authenticator active")
    communicator.waitForShutdown()


def main() -> int:
    LOG.parent.mkdir(parents=True, exist_ok=True)
    STATE.parent.mkdir(parents=True, exist_ok=True)
    install_authenticator()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
"""


def _auth_unit_text() -> str:
    return f"""[Unit]
Description=TAKS Mumble Voice PIN Authenticator
After=network-online.target {SERVICE}.service
Wants=network-online.target
Requires={SERVICE}.service

[Service]
Type=simple
ExecStart=/usr/bin/python3 {AUTH_BIN}
Restart=always
RestartSec=2
User=root
Group=root

[Install]
WantedBy=multi-user.target
"""


def _ensure_hex_secret(path: Path, nbytes: int = 32) -> str:
    try:
        current = path.read_text(encoding="utf-8").strip()
    except Exception:
        current = ""
    if current:
        return current

    secret = secrets.token_hex(nbytes)
    _run(["sudo", "install", "-d", "-o", "root", "-g", "root", "-m", "0750", str(path.parent)], check=True)
    _sudo_install_text(path, secret + "\n", mode="0600", owner="root", group="root")
    return secret


def _ensure_service_password_file(server_password: str) -> None:
    _run(["sudo", "install", "-d", "-o", "root", "-g", "root", "-m", "0750", str(SERVICE_PASSWORD_FILE.parent)], check=True)
    _sudo_install_text(
        SERVICE_PASSWORD_FILE,
        server_password + "\n",
        mode="0600",
        owner="root",
        group="root",
    )


def _install_voice_authenticator() -> None:
    _run(["sudo", "install", "-d", "-o", "root", "-g", "root", "-m", "0755", str(AUTH_BIN.parent)], check=True)
    _sudo_install_text(AUTH_BIN, AUTH_SCRIPT, mode="0755", owner="root", group="root")
    _sudo_install_text(AUTH_UNIT, _auth_unit_text(), mode="0644", owner="root", group="root")


def _node_unit_id(ctx: Context) -> str:
    fqdn = str(get_fqdn(ctx) or "").strip().lower()
    if not fqdn:
        raise RuntimeError("mumble_server.core: missing fqdn")
    return fqdn.split(".", 1)[0].strip()


def _desired_channels(ctx: Context) -> list[str]:
    unit = _node_unit_id(ctx)
    policy = Policy()
    topo = derive_voice_topology(policy.cfg, {"unit": unit, "policy_id": policy.policy_id})
    channels = [str(x).strip() for x in (topo.get("channels") or []) if str(x or "").strip()]
    if not channels:
        raise RuntimeError(f"mumble_server.core: voice topology produced no channels for unit={unit}")
    return channels


def _run(cmd: list[str], check: bool = True, capture: bool = False) -> subprocess.CompletedProcess[str]:
    return subprocess.run(cmd, check=check, text=True, capture_output=capture)


def _capture(cmd: list[str]) -> str:
    cp = _run(cmd, check=False, capture=True)
    return (cp.stdout or cp.stderr or "").strip()


def _sudo_install_text(
    dst: Path,
    content: str,
    mode: str = "0644",
    owner: str = "root",
    group: str = "root",
) -> None:
    with tempfile.NamedTemporaryFile("w", delete=False, suffix=".tmp") as tf:
        tf.write(content)
        tmp = tf.name
    try:
        _run(["sudo", "install", "-o", owner, "-g", group, "-m", mode, tmp, str(dst)], check=True)
    finally:
        try:
            os.unlink(tmp)
        except FileNotFoundError:
            pass


def _pkg_status() -> tuple[bool, str]:
    out = _capture(["sudo", "dpkg-query", "-W", "-f=${Status} ${Version}\n", PACKAGE])
    prefix = "install ok installed "
    if out.startswith(prefix):
        return True, out[len(prefix):].strip()
    return False, ""


def _systemctl_state(verb: str) -> str:
    return _capture(["sudo", "systemctl", verb, SERVICE])


def _lineages() -> list[Path]:
    base = Path("/etc/letsencrypt/live")
    out: list[Path] = []
    if not base.is_dir():
        return out
    for p in sorted(base.iterdir()):
        if not p.is_dir():
            continue
        if (p / "fullchain.pem").exists() and (p / "privkey.pem").exists():
            out.append(p)
    return out


def _configured_lineage() -> Path | None:
    if not HOOK.exists():
        return None
    try:
        s = HOOK.read_text(encoding="utf-8")
    except Exception:
        return None
    m = re.search(r'^LINEAGE="([^"]+)"$', s, flags=re.MULTILINE)
    if not m:
        return None
    p = Path(m.group(1))
    if (p / "fullchain.pem").exists() and (p / "privkey.pem").exists():
        return p
    return None


def _choose_lineage() -> Path:
    existing = _configured_lineage()
    if existing is not None:
        return existing

    found = _lineages()
    if len(found) == 1:
        return found[0]
    if not found:
        raise RuntimeError("no letsencrypt lineage with fullchain.pem + privkey.pem found under /etc/letsencrypt/live")
    raise RuntimeError(
        "multiple letsencrypt lineages found; refusing to guess: " + ", ".join(str(p) for p in found)
    )


def _set_kv_value(text: str, key: str, value: str) -> str:
    line = f"{key}={value}"
    pat = re.compile(rf"^[;#]?\s*{re.escape(key)}\s*=.*$", flags=re.MULTILINE)
    if pat.search(text):
        return pat.sub(line, text, count=1)
    if not text.endswith("\n"):
        text += "\n"
    return text + line + "\n"


def _get_kv_value(text: str, key: str) -> str:
    m = re.search(rf"^\s*{re.escape(key)}\s*=(.*)$", text, flags=re.MULTILINE)
    if not m:
        return ""
    return m.group(1).strip()


def _secret_group() -> str:
    try:
        grp.getgrnam("tak")
        return "tak"
    except KeyError:
        return "root"


def _generate_password(length: int = 20) -> str:
    alphabet = "ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789"
    return "".join(secrets.choice(alphabet) for _ in range(length))


def _read_text_if_exists(path: Path) -> str:
    if not path.exists():
        return ""
    return path.read_text(encoding="utf-8")


def _read_secret_text() -> str:
    current = _read_text_if_exists(SECRET_FILE)
    if current:
        return current
    legacy = _read_text_if_exists(LEGACY_SECRET_FILE)
    if legacy:
        return legacy
    return ""


def _ensure_secret_file() -> str:
    current = _read_secret_text()
    pw = _get_kv_value(current, SECRET_KEY)

    if not current:
        current = (
            "# canonical secrets for murmur/mumble-server\n"
            "# managed by tak-installer action mumble_server.core\n"
        )

    if not pw:
        pw = _generate_password()
        current = _set_kv_value(current, SECRET_KEY, pw)

    secret_group = _secret_group()
    _run(
        [
            "sudo",
            "install",
            "-d",
            "-o",
            "root",
            "-g",
            secret_group,
            "-m",
            "0750",
            str(SECRET_DIR),
        ],
        check=True,
    )
    _sudo_install_text(
        SECRET_FILE,
        current,
        mode="0640",
        owner="root",
        group=secret_group,
    )
    return pw


def _managed_config_text(lineage: Path, server_password: str, ice_secret: str) -> str:
    if not CONFIG.exists():
        raise RuntimeError(f"missing config file: {CONFIG}")

    s = CONFIG.read_text(encoding="utf-8")
    # The shared Murmur server password is intentionally blank. ATAK VX is
    # admitted by the external ICE authenticator using CoT UID/callsign presence.
    # Local/service clients use SERVICE_PASSWORD_FILE through the authenticator.
    s = _set_kv_value(s, "serverpassword", "")
    s = _set_kv_value(s, "ice", '"tcp -h 127.0.0.1 -p 6502"')
    s = _set_kv_value(s, "icesecretwrite", ice_secret)
    s = _set_kv_value(s, "autobanAttempts", "0")
    s = _set_kv_value(s, "autobanTimeframe", "0")
    s = _set_kv_value(s, "autobanTime", "0")
    s = _set_kv_value(s, "sslCert", str(TLS_DIR / "fullchain.pem"))
    s = _set_kv_value(s, "sslKey", str(TLS_DIR / "privkey.pem"))
    if (lineage / "chain.pem").exists():
        s = _set_kv_value(s, "sslCA", str(TLS_DIR / "chain.pem"))
    else:
        s = _set_kv_value(s, "sslCA", "")
    s = _set_kv_value(s, "certrequired", "false")
    return s


def _install_tls_material(lineage: Path) -> None:
    _run(
        [
            "sudo",
            "install",
            "-d",
            "-o",
            "root",
            "-g",
            "mumble-server",
            "-m",
            "0750",
            str(TLS_DIR),
        ],
        check=True,
    )
    _run(
        [
            "sudo",
            "install",
            "-o",
            "root",
            "-g",
            "root",
            "-m",
            "0644",
            str(lineage / "fullchain.pem"),
            str(TLS_DIR / "fullchain.pem"),
        ],
        check=True,
    )
    _run(
        [
            "sudo",
            "install",
            "-o",
            "root",
            "-g",
            "mumble-server",
            "-m",
            "0640",
            str(lineage / "privkey.pem"),
            str(TLS_DIR / "privkey.pem"),
        ],
        check=True,
    )
    if (lineage / "chain.pem").exists():
        _run(
            [
                "sudo",
                "install",
                "-o",
                "root",
                "-g",
                "root",
                "-m",
                "0644",
                str(lineage / "chain.pem"),
                str(TLS_DIR / "chain.pem"),
            ],
            check=True,
        )
    else:
        _run(["sudo", "rm", "-f", str(TLS_DIR / "chain.pem")], check=True)


def _hook_text(lineage: Path) -> str:
    return f"""#!/bin/sh
set -eu
LINEAGE="{lineage}"
DST="{TLS_DIR}"

install -d -o root -g mumble-server -m 0750 "$DST"
install -o root -g root -m 0644 "$LINEAGE/fullchain.pem" "$DST/fullchain.pem"
install -o root -g mumble-server -m 0640 "$LINEAGE/privkey.pem" "$DST/privkey.pem"

if [ -f "$LINEAGE/chain.pem" ]; then
  install -o root -g root -m 0644 "$LINEAGE/chain.pem" "$DST/chain.pem"
else
  rm -f "$DST/chain.pem"
fi

systemctl restart mumble-server
"""


def _backup(path: Path) -> Path | None:
    if not path.exists():
        return None
    bp = path.with_name(path.name + ".bak.taks")
    _run(["sudo", "cp", "-a", str(path), str(bp)], check=True)
    return bp


def _restore(src: Path | None, dst: Path) -> None:
    if src is None:
        return
    _run(["sudo", "cp", "-a", str(src), str(dst)], check=True)


def _seed_default_channels_if_empty(ctx: Context) -> bool:
    if not DB.exists():
        return False

    desired = _desired_channels(ctx)

    con = sqlite3.connect(str(DB))
    try:
        cur = con.cursor()
        rows = cur.execute(
            "select server_id, channel_id, parent_id, name, inheritacl from channels order by channel_id"
        ).fetchall()

        if len(rows) != 1:
            return False

        server_id, channel_id, parent_id, name, inheritacl = rows[0]
        if channel_id != 0 or name != "Root":
            return False

        next_id = 1
        for ch_name in desired:
            cur.execute(
                "insert into channels (server_id, channel_id, parent_id, name, inheritacl) values (?, ?, ?, ?, ?)",
                (server_id, next_id, 0, ch_name, 1),
            )
            next_id += 1

        con.commit()
        return True
    finally:
        con.close()



def _ensure_db_read_access() -> None:
    db_dir = DB.parent

    if db_dir.exists():
        _run(["sudo", "chgrp", "tak", str(db_dir)], check=False)
        _run(["sudo", "chmod", "2750", str(db_dir)], check=False)

        for cur in sorted(db_dir.glob("mumble-server.sqlite*")):
            if not cur.exists():
                continue
            _run(["sudo", "chgrp", "tak", str(cur)], check=False)
            _run(["sudo", "chmod", "0640", str(cur)], check=False)


@dataclass(frozen=True)
class _Action:
    ID: str = "mumble_server.core"

    def inspect(self, ctx: Context) -> int:
        installed, version = _pkg_status()
        enabled = _systemctl_state("is-enabled")
        active = _systemctl_state("is-active")
        cfg = str(CONFIG) if CONFIG.exists() else ""
        lineages = _lineages()
        chosen = ""
        try:
            chosen = str(_choose_lineage())
        except Exception as e:
            chosen = f"ERROR: {e}"

        secret_present = SECRET_FILE.exists()
        legacy_secret_present = LEGACY_SECRET_FILE.exists()
        secret_text = _read_secret_text()
        password = _get_kv_value(secret_text, SECRET_KEY)
        password_len = len(password) if password else 0

        print("Mumble server core (package + tls + canonical secret + systemd)")
        print(f"  package: {PACKAGE}")
        print(f"  installed: {str(installed).lower()}")
        print(f"  version: {version}")
        print(f"  service enabled: {enabled}")
        print(f"  service active: {active}")
        print(f"  config path: {cfg}")
        print(f"  tls dir: {TLS_DIR}")
        print(f"  canonical secret file: {SECRET_FILE}")
        print(f"  canonical secret present: {str(secret_present).lower()}")
        print(f"  legacy secret file: {LEGACY_SECRET_FILE}")
        print(f"  legacy secret present: {str(legacy_secret_present).lower()}")
        print(f"  canonical {SECRET_KEY} length: {password_len}")
        print(f"  ice secret file: {ICE_SECRET_FILE}")
        print(f"  service password file: {SERVICE_PASSWORD_FILE}")
        print(f"  auth service: {AUTH_SERVICE}")
        print(f"  auth bin: {AUTH_BIN}")
        print(f"  hook path: {HOOK}")
        print(f"  db path: {DB}")
        print(f"  default channels: {', '.join(DEFAULT_CHANNELS)}")
        print("  lineages found:")
        if lineages:
            for p in lineages:
                print(f"    {p}")
        else:
            print("    (none)")
        print(f"  chosen lineage: {chosen}")
        print("  listeners:")
        ss = _capture(["sudo", "ss", "-luntp"])
        lines = [line for line in ss.splitlines() if "64738" in line]
        if lines:
            for line in lines:
                print(f"    {line}")
        else:
            print("    (no :64738 listener found)")
        print("  dry-run: no changes performed.")
        return 0

    def apply(self, ctx: Context) -> int:
        config_backup: Path | None = None
        hook_backup: Path | None = None
        secret_backup: Path | None = None
        db_backup: Path | None = None

        try:
            _run(["sudo", "apt-get", "update"], check=True)
            _run(
                [
                    "sudo",
                    "env",
                    "DEBIAN_FRONTEND=noninteractive",
                    "apt-get",
                    "install",
                    "-y",
                    *PACKAGES,
                ],
                check=True,
            )

            if not CONFIG.exists():
                raise RuntimeError(f"expected config file after install: {CONFIG}")

            lineage = _choose_lineage()

            config_backup = _backup(CONFIG)
            hook_backup = _backup(HOOK)
            secret_backup = _backup(SECRET_FILE)

            server_password = _ensure_secret_file()
            ice_secret = _ensure_hex_secret(ICE_SECRET_FILE)
            _ensure_service_password_file(server_password)
            _install_tls_material(lineage)

            cfg_text = _managed_config_text(lineage, server_password, ice_secret)
            _sudo_install_text(
                CONFIG,
                cfg_text,
                mode="0640",
                owner="root",
                group="mumble-server",
            )

            _run(["sudo", "mkdir", "-p", str(HOOK.parent)], check=True)
            _sudo_install_text(HOOK, _hook_text(lineage), mode="0755")
            _install_voice_authenticator()

            _run(["sudo", "systemctl", "stop", AUTH_SERVICE], check=False)
            _run(["sudo", "systemctl", "stop", SERVICE], check=False)
            db_backup = _backup(DB)
            seeded = _seed_default_channels_if_empty(ctx)
            _ensure_db_read_access()

            _run(["sudo", "systemctl", "daemon-reload"], check=True)
            _run(["sudo", "systemctl", "enable", "--now", SERVICE], check=True)
            _run(["sudo", "systemctl", "restart", SERVICE], check=True)
            _run(["sudo", "systemctl", "enable", "--now", AUTH_SERVICE], check=True)
            _run(["sudo", "systemctl", "restart", AUTH_SERVICE], check=True)

            active = _systemctl_state("is-active")
            if active != "active":
                raise RuntimeError(f"{SERVICE} is not active after apply: {active}")

            auth_active = _capture(["sudo", "systemctl", "is-active", AUTH_SERVICE])
            if auth_active != "active":
                raise RuntimeError(f"{AUTH_SERVICE} is not active after apply: {auth_active}")

            version = _pkg_status()[1]
            print(
                f"applied: mumble_server.core "
                f"(changed=true, version={version}, lineage={lineage}, secret_file={SECRET_FILE}, "
                f"ice_secret_file={ICE_SECRET_FILE}, auth_service={AUTH_SERVICE}, "
                f"seeded_channels={str(seeded).lower()})"
            )
            return 0

        except Exception as e:
            print(f"ERROR: mumble_server.core failed: {e}")
            print("ERROR: attempting rollback of config + hook + canonical secret...")
            try:
                _restore(config_backup, CONFIG)
            except Exception as re:
                print(f"ERROR: rollback config failed: {re}")
            try:
                _restore(hook_backup, HOOK)
            except Exception as re:
                print(f"ERROR: rollback hook failed: {re}")
            try:
                _restore(secret_backup, SECRET_FILE)
            except Exception as re:
                print(f"ERROR: rollback secret failed: {re}")
            try:
                _restore(db_backup, DB)
            except Exception as re:
                print(f"ERROR: rollback db failed: {re}")
            try:
                _run(["sudo", "systemctl", "restart", SERVICE], check=False)
                _run(["sudo", "systemctl", "restart", AUTH_SERVICE], check=False)
            except Exception:
                pass
            return 2


ACTION = _Action()
