from __future__ import annotations

import os
import secrets
import subprocess
from pathlib import Path

from tak_installer.util import log

SECRETS_DIR = Path("/opt/tak/tools/takctl/secrets")
DB_ENV = SECRETS_DIR / "db.env"

DEFAULTS = {
    "TAKCTL_DB_HOST": "127.0.0.1",
    "TAKCTL_DB_PORT": "5432",
    "TAKCTL_DB_NAME": "cot",
    "TAKCTL_DB_USER": "takctl_ro",
}


def _parse_env(text: str) -> dict[str, str]:
    out: dict[str, str] = {}
    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        k, v = line.split("=", 1)
        out[k.strip()] = v.strip()
    return out


def _write_atomic(path: Path, data: str, mode: int) -> None:
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(data, encoding="utf-8")
    os.chmod(tmp, mode)
    tmp.replace(path)


def _run(cmd: list[str], *, check: bool = True) -> subprocess.CompletedProcess[str]:
    return subprocess.run(cmd, text=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, check=check)


def _ensure_db_env() -> dict[str, str]:
    SECRETS_DIR.mkdir(parents=True, exist_ok=True)

    existing: dict[str, str] = {}
    if DB_ENV.exists():
        existing = _parse_env(DB_ENV.read_text(encoding="utf-8"))

    merged = DEFAULTS.copy()
    merged.update(existing)

    # Generate once if missing; never rotate silently.
    if "TAKCTL_DB_PASSWORD" not in merged or not merged["TAKCTL_DB_PASSWORD"].strip():
        merged["TAKCTL_DB_PASSWORD"] = secrets.token_urlsafe(24)

    lines = [f"{k}={v}" for k, v in sorted(merged.items())]
    content = "# Auto-generated by takctl-db-env\n" + "\n".join(lines) + "\n"

    _write_atomic(DB_ENV, content, 0o640)
    _run(["chown", "-R", "tak:tak", str(SECRETS_DIR)], check=False)

    log.info("takctl-db-env: ensured %s", DB_ENV)
    return merged


def _sync_postgres_role(cfg: dict[str, str]) -> None:
    """
    Make Postgres accept the creds we just wrote.

    This is installer-owned wiring: db.env is the source of truth.

    Safe behavior:
      - create role if missing
      - set role password to match db.env
      - grant CONNECT on DB
      - grant USAGE on public schema
      - grant SELECT on all tables in public
      - set default privileges for future tables (best-effort)

    NOTE: This assumes local Postgres and ability to sudo -u postgres.
    """
    host = cfg.get("TAKCTL_DB_HOST", "").strip()
    port = cfg.get("TAKCTL_DB_PORT", "").strip()
    db = cfg.get("TAKCTL_DB_NAME", "").strip()
    user = cfg.get("TAKCTL_DB_USER", "").strip()
    pw = cfg.get("TAKCTL_DB_PASSWORD", "").strip()

    if not (host and port and db and user and pw):
        log.info("takctl-db-env: postgres sync skipped (incomplete db.env)")
        return

    # Only try local postgres wiring. If someone points host elsewhere, don't assume superuser access.
    if host not in ("127.0.0.1", "localhost"):
        log.info("takctl-db-env: postgres sync skipped (non-local host=%s)", host)
        return

    # psql presence check
    if subprocess.run(["bash", "-lc", "command -v psql >/dev/null 2>&1"]).returncode != 0:
        log.info("takctl-db-env: postgres sync skipped (psql not installed)")
        return

    sql = f"""
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '{user}') THEN
    CREATE ROLE {user} LOGIN;
  END IF;
END
$$;

ALTER ROLE {user} WITH LOGIN PASSWORD '{pw}';

GRANT CONNECT ON DATABASE {db} TO {user};

\\connect {db}

GRANT USAGE ON SCHEMA public TO {user};
GRANT SELECT ON ALL TABLES IN SCHEMA public TO {user};

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO {user};
"""

    # Execute as postgres superuser
    p = subprocess.run(
        ["sudo", "-u", "postgres", "psql", "-v", "ON_ERROR_STOP=1", "-q"],
        input=sql,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
    )
    if p.returncode != 0:
        # Don't brick the installer if the DB isn't ready yet, but do log loudly.
        log.info("takctl-db-env: postgres sync failed (rc=%s):\n%s", p.returncode, (p.stdout or "").strip())
        return

    log.info("takctl-db-env: postgres role synced for %s on db=%s", user, db)


def _verify_login(cfg: dict[str, str]) -> None:
    """
    Best-effort login verification as 'tak' using db.env values.
    Never hard-fail apply; just logs.
    """
    host = cfg["TAKCTL_DB_HOST"]
    port = cfg["TAKCTL_DB_PORT"]
    db = cfg["TAKCTL_DB_NAME"]
    user = cfg["TAKCTL_DB_USER"]
    pw = cfg["TAKCTL_DB_PASSWORD"]

    cmd = (
        f'PGPASSWORD="{pw}" psql -h "{host}" -p "{port}" -U "{user}" -d "{db}" '
        f'-v ON_ERROR_STOP=1 -qtA -c "select 1;"'
    )
    p = subprocess.run(["sudo", "-u", "tak", "bash", "-lc", cmd], text=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    if p.returncode == 0:
        log.info("takctl-db-env: verified DB login for %s", user)
    else:
        log.info("takctl-db-env: DB login verification failed (rc=%s):\n%s", p.returncode, (p.stdout or "").strip())


def apply(ctx) -> None:
    cfg = _ensure_db_env()
    _sync_postgres_role(cfg)
    _verify_login(cfg)


class _Action:
    ID = "takctl-db-env"

    def inspect(self, ctx) -> int:
        log.info("Inspecting %s action...", self.ID)
        return 0

    def apply(self, ctx) -> int:
        log.info("Applying %s action...", self.ID)
        apply(ctx)
        return 0


ACTION = _Action()
