from __future__ import annotations

import os
import subprocess
from pathlib import Path

from tak_installer.util import log

ETC_TAK = Path("/opt/tak/etc")
OLD_SYSTEMD_DROPIN = Path("/etc/systemd/system/takctl-web.service.d/40-onboarding-email.conf")
MSMTPRC = Path("/etc/msmtprc")
MSMTP_PASS = ETC_TAK / "msmtp.password"


def _truthy(v: str | None, default: bool = False) -> bool:
    s = (v or "").strip().lower()
    if not s:
        return default
    return s in ("1", "true", "yes", "y", "on")


def _cfg(ctx) -> dict[str, str]:
    env = dict(ctx.env or {})

    host = (env.get("TAKS_SMTP_HOST") or "").strip()
    port = (env.get("TAKS_SMTP_PORT") or "").strip() or "587"
    user = (env.get("TAKS_SMTP_USER") or "").strip()
    password = (env.get("TAKS_SMTP_PASSWORD") or "").strip()
    from_addr = (
        (env.get("TAKS_ONBOARDING_FROM") or "").strip()
        or (env.get("TAKS_EMAIL_FROM") or "").strip()
    )
    tls = "on" if _truthy(env.get("TAKS_SMTP_TLS"), True) else "off"
    starttls = "on" if _truthy(env.get("TAKS_SMTP_STARTTLS"), True) else "off"

    auth_env = (env.get("TAKS_SMTP_AUTH") or "").strip().lower()
    if auth_env in ("on", "off"):
        auth = auth_env
    else:
        auth = "on" if user else "off"

    return {
        "host": host,
        "port": port,
        "user": user,
        "password": password,
        "from_addr": from_addr,
        "tls": tls,
        "starttls": starttls,
        "auth": auth,
    }


def _write(path: Path, content: str, mode: int) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    os.chmod(path, mode)


def _chown_root_tak(path: Path) -> None:
    subprocess.run(["chown", "root:tak", str(path)], check=False)


def _render_msmtprc(cfg: dict[str, str]) -> str:
    lines: list[str] = [
        "# Auto-generated by takctl-msmtp-env",
        "defaults",
        "syslog LOG_MAIL",
        "tls_trust_file /etc/ssl/certs/ca-certificates.crt",
        "",
        "account default",
        f"host {cfg['host']}",
        f"port {cfg['port']}",
        f"tls {cfg['tls']}",
        f"tls_starttls {cfg['starttls']}",
        f"auth {cfg['auth']}",
    ]

    if cfg["from_addr"]:
        lines.append(f"from {cfg['from_addr']}")

    if cfg["auth"] == "on":
        if cfg["user"]:
            lines.append(f"user {cfg['user']}")
        if cfg["password"]:
            lines.append(f"passwordeval cat {MSMTP_PASS}")
        else:
            lines.append("# WARNING: auth=on but no TAKS_SMTP_PASSWORD was provided")

    lines.append("")
    return "\n".join(lines)


def _clear_if_exists(path: Path) -> None:
    try:
        if path.exists():
            path.unlink()
    except Exception:
        pass


def apply(ctx) -> None:
    cfg = _cfg(ctx)

    # old env-driven takctl-web dropin must die
    _clear_if_exists(OLD_SYSTEMD_DROPIN)

    if not cfg["host"]:
        log.info("takctl-msmtp-env: TAKS_SMTP_HOST not set; skipping msmtp config")
        return

    ETC_TAK.mkdir(parents=True, exist_ok=True)

    msmtprc = _render_msmtprc(cfg)
    _write(MSMTPRC, msmtprc + "\n", 0o640)
    _chown_root_tak(MSMTPRC)

    if cfg["password"]:
        _write(MSMTP_PASS, cfg["password"] + "\n", 0o640)
        _chown_root_tak(MSMTP_PASS)
    else:
        _clear_if_exists(MSMTP_PASS)

    log.info(
        "takctl-msmtp-env: wrote %s (host=%s port=%s auth=%s from=%s)",
        MSMTPRC,
        cfg["host"],
        cfg["port"],
        cfg["auth"],
        cfg["from_addr"] or "-",
    )


class _Action:
    ID = "takctl-msmtp-env"

    def inspect(self, ctx) -> int:
        cfg = _cfg(ctx)
        log.info("Inspecting %s action...", self.ID)
        log.info("  host: %s", cfg["host"] or "(unset)")
        log.info("  port: %s", cfg["port"])
        log.info("  auth: %s", cfg["auth"])
        log.info("  from: %s", cfg["from_addr"] or "(unset)")
        log.info("  msmtprc: %s", MSMTPRC)
        log.info("  password file: %s", MSMTP_PASS)
        log.info("  old takctl-web dropin removed: %s", OLD_SYSTEMD_DROPIN)
        return 0

    def apply(self, ctx) -> int:
        log.info("Applying %s action...", self.ID)
        apply(ctx)
        return 0


ACTION = _Action()
